//
// recommend do not edit this file
// --------------------------------------------------
//

var $ = jQuery.noConflict();

(function($) {
  'use strict';

//
// function start
// --------------------------------------------------
//

  var BONEFISHCODE = {
    ready: function() {
      BONEFISHCODE.fn_deviceDetect();
      BONEFISHCODE.fn_form();
      BONEFISHCODE.fn_utility();
      BONEFISHCODE.fn_gallery();
      BONEFISHCODE.fn_sticky();
      BONEFISHCODE.fn_scrollTo();
      BONEFISHCODE.fn_scrollspy();
      BONEFISHCODE.fn_slideshow();
      BONEFISHCODE.fn_youtube();
      BONEFISHCODE.fn_popup();
      BONEFISHCODE.fn_cloud();
      BONEFISHCODE.fn_carousel();
      BONEFISHCODE.fn_animate();
      BONEFISHCODE.fn_navbar();
    },
    load: function() {
      BONEFISHCODE.fn_pageLoader();
      BONEFISHCODE.fn_hero();
      BONEFISHCODE.fn_audio();
    },
    scroll: function() {
    },
    resize: function() {
    },
    orientationchange: function() {
      fn_hero();
    },

//
// page loader
// --------------------------------------------------
//

    fn_pageLoader: function() {
      var $el = $('.page-loader');

      if ($el.length) {
        $el.velocity('fadeOut', {
          duration: pageLoaderDuration,
          easing: easeInOutQuart,
          complete: function() {
            $(this).remove();
            $body.addClass('is-loaded');
          }
        });
      }
    },

//
// animate
// --------------------------------------------------
//

    fn_animate: function() {
      window.sr = ScrollReveal({
        duration: 50,
        scale: 1,
        mobile: false,
        reset: true,
        viewFactor: 0.1
      });

      if (sr.isSupported()) {
        document.documentElement.classList.add('sr');

        $(window).on('load', function() {
          setTimeout(function() {
            if ($('[data-sr=top]').length) {
              sr.reveal('[data-sr=top]', {origin: 'top'});
            }
            if ($('[data-sr=right]').length) {
              sr.reveal('[data-sr=right]', {origin: 'right'});
            }
            if ($('[data-sr=bottom]').length) {
              sr.reveal('[data-sr=bottom]', {origin: 'bottom'});
            }
            if ($('[data-sr=left]').length) {
              sr.reveal('[data-sr=left]', {origin: 'left'});
            }
          }, pageLoaderDuration);
        });
      }

      if (!isIE9 && !isMobile) {
        $(window).on('load', function() {
          setTimeout(function() {
            var wow = new WOW();
            wow.init();

            $('.text-animate').textillate({
              in: {
                effect: 'fadeInUp',
                delayScale: .3,
                shuffle: true,
              }
            });
          }, pageLoaderDuration);
        });
      }
    },

//
// navbar
// --------------------------------------------------
//

    fn_navbar: function() {
      $(window).on('load resize orientationchange', function() {
        $('.navbar-collapse').css({ maxHeight: $(window).height() - $('.navbar-header').height() + 'px' });
      });
    },

//
// scrollspy
// --------------------------------------------------
//

    fn_scrollspy: function() {
      var target = '#siteNavbar';
      var offset = $(target).find('.navbar-header').outerHeight() + 1;

      $body.scrollspy({
        target: target,
        offset: parseInt(offset)
      });
    },

//
// scroll to
// --------------------------------------------------
//

    fn_scrollTo: function() {
      $('[data-smooth-scroll="true"]').on('click', function(e) {
        e.preventDefault();

        var id = $(this).attr('href');

        if ($(id).is(':visible')) {
          var offset = $(id).offset().top - $('#siteNavbar').find('.navbar-header').outerHeight();

          $('html, body').stop().animate({
            scrollTop: offset
          }, 1250);
        }
      });
    },

//
// sticky
// --------------------------------------------------
//

    fn_sticky: function() {
      $(window).on('load scroll resize', function() {
        var offset = $('#siteNavbar').find('.navbar-header').outerHeight();

        if ($(window).scrollTop() >= 88) {
          $html.addClass('is-scrolled');
        } else {
          $html.removeClass('is-scrolled');
        }
      });
    },

//
// hero
// --------------------------------------------------
//

    fn_hero: function() {
      var $hero = $('.js-hero, .home-hero');

      $hero.css('height', $(window).height() + 'px');
    },

//
// carousel
// --------------------------------------------------
//

    fn_carousel: function() {
      $('#screenshotCarousel').imagesLoaded().always(function(instance) {
        var $carousel = $('#screenshotCarousel');

        $carousel.slick({
          centerMode: true,
          centerPadding: 0,
          slidesToShow: 3,
          swipeToSlide: true,
          responsive: [
            {
              breakpoint: 1200,
              settings: {
                slidesToShow: 3
              }
            },
            {
              breakpoint: 992,
              settings: {
                slidesToShow: 3
              }
            },
            {
              breakpoint: 768,
              settings: {
                slidesToShow: 3
              }
            },
            {
              breakpoint: 480,
              settings: {
                slidesToShow: 1,
                slidesToScroll: 1
              }
            }
          ]
        });
      });
	  
	  
	      $('#partnersCarousel').imagesLoaded().always(function(instance) {
        var $carousel = $('#partnersCarousel');

        $carousel.slick({
          centerMode: true,
          centerPadding: 15,
          slidesToShow: 8,
          swipeToSlide: true,
		    slidesToScroll: 1,
  autoplay: true,
  autoplaySpeed: 1000,
          responsive: [
            {
              breakpoint: 1200,
              settings: {
                slidesToShow: 8
              }
            },
            {
              breakpoint: 992,
              settings: {
                slidesToShow: 7
              }
            },
            {
              breakpoint: 768,
              settings: {
                slidesToShow: 6
              }
            },
            {
              breakpoint: 480,
              settings: {
                slidesToShow: 3,
                slidesToScroll: 1
              }
            }
          ]
        });
      });
	  
	  
    },

//
// gallery
// --------------------------------------------------
//

    fn_gallery: function() {
      $('.popup-gallery').each(function() {
        var $popup = $(this);

        $popup.magnificPopup({
          delegate: '.popup-gallery-link',
          type: 'image',
          gallery: {
            enabled: true,
            tCounter: ''
          },
          midClick: true,
          fixedContentPos: true,
          fixedBgPos: true
        });
      });
    },

//
// popup
// --------------------------------------------------
//

    fn_popup: function() {
      var $popupIframe = $('.popup-youtube, .popup-vimeo, .popup-gmaps');

      $popupIframe.each(function() {
        var $this = $(this);

        $popupIframe.magnificPopup({
          items: {
            src: $popupIframe.data('mfp-src'),
          },
          type: 'iframe',
          midClick: true,
          fixedContentPos: true,
          fixedBgPos: true,
          callbacks: {
            beforeOpen: function() {
              if (!$this.hasClass('popup-gmaps')) {
                $('.js-bg-youtube-is-playing').each(function() {
                  $(this).YTPPause().toggleClass('js-bg-youtube-is-playing --js-bg-youtube-is-paused');
                });

                if ($body.hasClass('audio-playing')) {
                  $('#audioPlayer')[0].pause();
                  $body.removeClass('audio-playing').addClass('audio-paused --audio-paused');
                }
              }
            },
            afterClose: function() {
              if (!$this.hasClass('popup-gmaps')) {
                $('.--js-bg-youtube-is-paused').each(function() {
                  $(this).YTPPlay().toggleClass('--js-bg-youtube-is-paused js-bg-youtube-is-playing');
                });

                if ($body.hasClass('audio-paused --audio-paused')) {
                  $('#audioPlayer')[0].play();
                  $body.removeClass('audio-paused --audio-paused').addClass('audio-playing');
                }
              }
            },
          }
        });
      });

      var $popupInline = $('.popup-inline');

      $popupInline.each(function() {
        var $popupInline = $(this);

        $popupInline.magnificPopup({
          type: 'inline',
          midClick: true,
          closeBtnInside: true,
          fixedContentPos: true,
          fixedBgPos: true,
        });
      });
    },

//
// audio
// --------------------------------------------------
//

    fn_audio: function() {
      if ($('#audioPlayer').length) {
        var $player = $('#audioPlayer')[0];
        var $toggle = $('.audio-toggle').find('a');

        if (isMobile) {
          $body.addClass('audio-paused');
          $player.pause();
        } else {
          $body.addClass('audio-playing');
          $player.play();
        }

        $toggle.on('click', function(e) {
          e.preventDefault();

          if ($player.paused) {
            $body.removeClass('audio-paused').addClass('audio-playing');
            $player.play();

          } else {
            $body.removeClass('audio-playing').addClass('audio-paused');
            $player.pause();
          }
        });
      }
    },

//
// utility
// --------------------------------------------------
//

    fn_utility: function() {
      $('[data-opacity]').each(function() {
        var $this = $(this);
        $this.css('opacity', $this.data('opacity'));
      });

      $('[data-bg-color]').each(function() {
        var $this = $(this);
        $this.css('background-color', $this.data('bg-color'));
      });

      $('[data-bg-img]').each(function() {
        var $this = $(this);
        $this.css('background-image', 'url(' + $this.data('bg-img') + ')');
      });

      $('[data-bg-img-mobile]').each(function() {
        if (isMobile) {
          var $this = $(this);
          $this.css('background-image', 'url(' + $this.data('bg-img-mobile') + ')');
        }
      });

      $('[data-bg-img-desktop]').each(function() {
        if (isDesktop) {
          var $this = $(this);
          $this.css('background-image', 'url(' + $this.data('bg-img-desktop') + ')');
        }
      });
    },

//
// device detect
// --------------------------------------------------

    fn_deviceDetect: function() {
      if ($html.hasClass('desktop')) {
        $html.addClass('is-desktop');
        isMobile = false;
        isDesktop = true;
      } else {
        $html.addClass('is-mobile');
        isMobile = true;
        isDesktop = false;
      }

      if ($html.hasClass('ie9')) {
        isIE9 = true;
      }
    },

//
// slideshow
// --------------------------------------------------

    fn_slideshow: function() {
      if ($('#homeBgSlideshow').is(':visible')) {
        $('#homeBgSlideshow').vegas({
          slides: [
            { src: 'assets/img/home/home-bg-slide-1.jpg' },
            { src: 'assets/img/home/home-bg-slide-2.jpg' },
            { src: 'assets/img/home/home-bg-slide-3.jpg' },
          ],
          delay: 7000
        });
      }
    },

//
// cloud
// --------------------------------------------------
//

    fn_cloud: function() {
      if ($('#homeBgCloud').is(':visible')) {
        $('#homeBgCloud').find('.cloud').each(function() {
         var $this = $(this);

          (function cloud() {
            $this.velocity({
              translateZ: '0',
              translateX: ['-100%', '100%']
            }, {
              duration: $this.data('duration'),
              easing: 'linear',
              queue: false
            });
            setTimeout(cloud, $this.data('duration'));
          })();
        });
      }
    },

//
// form
// --------------------------------------------------
//

    fn_form: function() {
      $('.form').each(function() {
        var $form = $(this);
        var $formControl = $form.find('.form-control');
        var $formNotify = $form.find('.form-notify');
        var formUrl = $form.data('action');

        $formControl.each(function() {
          var $this = $(this);

          $this.on('focus', function() {
            $(this).parent('.form-group').addClass('focus');
          }).on('blur', function() {
            $(this).parent('.form-group').removeClass('focus');
          });
        });

        $form.validate({
          onclick: false,
          onfocusout: false,
          onkeyup: false,
          ignore: '.ignore',
          rules: {
            fname: {
              required: true
            },
            lname: {
              required: true
            },
            name: {
              required: true
            },
            email: {
              required: true,
              email: true
            },
			 mobile: {
              required: true,
			  number: true,
			   minlength:9,
              maxlength:10
			  
            },
            message: {
              required: true
            },
            agree: {
              required: true
            },
          },
          errorPlacement: function(error, element) {},
          highlight: function(element) {
            $(element).closest('.form-group').addClass('error');
          },
          unhighlight: function(element) {
            $(element).closest('.form-group').removeClass('error');
          },
          submitHandler: function(form) {
            $.ajax({
              type: 'POST',
              dataType: 'json',
              url: formUrl,
              cache: false,
              data: $form.serialize(),
              success: function(data) {
                if (data.type != 'success') {
                  $formNotify.html('<span class="form-icon-error"></span> ' + data.msg).show();
                } else {
                  $form.validate().resetForm();
                  $form[0].reset();
                  $form.find('.error').removeClass('error');
                  $form.addClass('successfully');
                  $form.find('button').blur();
                  $formNotify.html('<span class="form-icon-success"></span> ' + data.msg).show();
                }
              },
              error: function(XMLHttpRequest, textStatus, errorThrown) {
                $formNotify.html('<span class="form-icon-error"></span> An error occurred. Please try again later.').show();
              },
            });
          },
          invalidHandler: function(event, validator) {
            var errors = validator.numberOfInvalids();

            if (errors) {
              var message = errors == 1 ?
              '<span class="form-icon-error"></span>You missed 1 field. It has been highlighted.' :
              '<span class="form-icon-error"></span>You missed ' + errors + ' fields. They have been highlighted.';
              $formNotify.html(message).show();
            }
          }
        });
      });
    },

//
// youtube
// --------------------------------------------------

    fn_youtube: function() {
      if ($('#homeBgYoutube').is(':visible')) {
        var $player = $('#homeBgYoutubePlayer');

        if (isMobile) {
          $('#homeBgYoutubePlaceholder').remove();
        } else {
          $('#homeBgYoutubeFallback').remove();
          $player.YTPlayer();
          $player.on('YTPPlay', function() {
            $(this).addClass('js-bg-youtube-is-playing').removeClass('js-bg-youtube-is-paused');
          });
          $player.on('YTPPause', function() {
            $(this).addClass('js-bg-youtube-is-paused').removeClass('js-bg-youtube-is-playing');
          });
        }
      }
    },

//
// end of BONEFISHCODE
// --------------------------------------------------

  };

//
// global variable
// --------------------------------------------------
//

  var $html = $('html'),
      $body = $('body'),
      easeInOutQuart = [0.770, 0.000, 0.175, 1.000],
      isMobile,
      isDesktop,
      isIE9,
      pageLoaderDuration = 50;
      if ($('.page-loader').length && typeof BONEFISHCODE.fn_pageLoader !== 'undefined' && $.isFunction(BONEFISHCODE.fn_pageLoader)) {
        pageLoaderDuration = 50;
      }

//
// init
// --------------------------------------------------

	$(function() {
		BONEFISHCODE.ready();

    $(window).on('scroll', function() {
      BONEFISHCODE.scroll();
    });

    $(window).on('resize', function() {
      BONEFISHCODE.resize();
    });

    $(window).on('load', function() {
      BONEFISHCODE.load();
    });
	});

//
// function end
// --------------------------------------------------
//

})(jQuery);
